[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 200
verbosity = 2

[profile.anvil]
eth_rpc_url = "http://127.0.0.1:8545"

[profile.sepolia]
eth_rpc_url = "${ETH_RPC_URL}"

[rpc_endpoints]
sepolia = "${INFURA_SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}", chain = 11155111, url = "https://api-sepolia.etherscan.io/api" }
